/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeTerminateEmployeeRequest
 */
public class EmployeeTerminateEmployeeRequestTest {
    private final EmployeeTerminateEmployeeRequest model = new EmployeeTerminateEmployeeRequest();

    /**
     * Model tests for EmployeeTerminateEmployeeRequest
     */
    @Test
    public void testEmployeeTerminateEmployeeRequest() {
        // TODO: test EmployeeTerminateEmployeeRequest
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'terminationReasonId'
     */
    @Test
    public void terminationReasonIdTest() {
        // TODO: test terminationReasonId
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

}
