/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeGetTerminatedEmployeeResponseDataTermination
 */
public class EmployeeGetTerminatedEmployeeResponseDataTerminationTest {
    private final EmployeeGetTerminatedEmployeeResponseDataTermination model = new EmployeeGetTerminatedEmployeeResponseDataTermination();

    /**
     * Model tests for EmployeeGetTerminatedEmployeeResponseDataTermination
     */
    @Test
    public void testEmployeeGetTerminatedEmployeeResponseDataTermination() {
        // TODO: test EmployeeGetTerminatedEmployeeResponseDataTermination
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

}
