/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeGetTerminatedEmployeeResponseDataTermination;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeGetTerminatedEmployeeResponseData
 */
public class EmployeeGetTerminatedEmployeeResponseDataTest {
    private final EmployeeGetTerminatedEmployeeResponseData model = new EmployeeGetTerminatedEmployeeResponseData();

    /**
     * Model tests for EmployeeGetTerminatedEmployeeResponseData
     */
    @Test
    public void testEmployeeGetTerminatedEmployeeResponseData() {
        // TODO: test EmployeeGetTerminatedEmployeeResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'terminationDate'
     */
    @Test
    public void terminationDateTest() {
        // TODO: test terminationDate
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'pictureUrl'
     */
    @Test
    public void pictureUrlTest() {
        // TODO: test pictureUrl
    }

    /**
     * Test the property 'employmentStartDate'
     */
    @Test
    public void employmentStartDateTest() {
        // TODO: test employmentStartDate
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'termination'
     */
    @Test
    public void terminationTest() {
        // TODO: test termination
    }

}
