/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IntegrationsTransferContractInformationToVikarinaResponseData
 */
public class IntegrationsTransferContractInformationToVikarinaResponseDataTest {
    private final IntegrationsTransferContractInformationToVikarinaResponseData model = new IntegrationsTransferContractInformationToVikarinaResponseData();

    /**
     * Model tests for IntegrationsTransferContractInformationToVikarinaResponseData
     */
    @Test
    public void testIntegrationsTransferContractInformationToVikarinaResponseData() {
        // TODO: test IntegrationsTransferContractInformationToVikarinaResponseData
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'workStartDate'
     */
    @Test
    public void workStartDateTest() {
        // TODO: test workStartDate
    }

    /**
     * Test the property 'contractNumber'
     */
    @Test
    public void contractNumberTest() {
        // TODO: test contractNumber
    }

    /**
     * Test the property 'terminationDate'
     */
    @Test
    public void terminationDateTest() {
        // TODO: test terminationDate
    }

    /**
     * Test the property 'employmentStatus'
     */
    @Test
    public void employmentStatusTest() {
        // TODO: test employmentStatus
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
