/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IntegrationsTransferTimeScheduleInformationResponseData
 */
public class IntegrationsTransferTimeScheduleInformationResponseDataTest {
    private final IntegrationsTransferTimeScheduleInformationResponseData model = new IntegrationsTransferTimeScheduleInformationResponseData();

    /**
     * Model tests for IntegrationsTransferTimeScheduleInformationResponseData
     */
    @Test
    public void testIntegrationsTransferTimeScheduleInformationResponseData() {
        // TODO: test IntegrationsTransferTimeScheduleInformationResponseData
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'standBy'
     */
    @Test
    public void standByTest() {
        // TODO: test standBy
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'nightours'
     */
    @Test
    public void nightoursTest() {
        // TODO: test nightours
    }

    /**
     * Test the property 'costCenterCode'
     */
    @Test
    public void costCenterCodeTest() {
        // TODO: test costCenterCode
    }

    /**
     * Test the property 'overtimeTitle'
     */
    @Test
    public void overtimeTitleTest() {
        // TODO: test overtimeTitle
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
