/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveManagementGetTimeOffBalancesResponseDataInner
 */
public class LeaveManagementGetTimeOffBalancesResponseDataInnerTest {
    private final LeaveManagementGetTimeOffBalancesResponseDataInner model = new LeaveManagementGetTimeOffBalancesResponseDataInner();

    /**
     * Model tests for LeaveManagementGetTimeOffBalancesResponseDataInner
     */
    @Test
    public void testLeaveManagementGetTimeOffBalancesResponseDataInner() {
        // TODO: test LeaveManagementGetTimeOffBalancesResponseDataInner
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    public void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'used'
     */
    @Test
    public void usedTest() {
        // TODO: test used
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

}
