/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LeaveManagementListTimeOffRequestsResponseDataInnerFieldsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveManagementListTimeOffRequestsResponseDataInner
 */
public class LeaveManagementListTimeOffRequestsResponseDataInnerTest {
    private final LeaveManagementListTimeOffRequestsResponseDataInner model = new LeaveManagementListTimeOffRequestsResponseDataInner();

    /**
     * Model tests for LeaveManagementListTimeOffRequestsResponseDataInner
     */
    @Test
    public void testLeaveManagementListTimeOffRequestsResponseDataInner() {
        // TODO: test LeaveManagementListTimeOffRequestsResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    public void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'isMultiDate'
     */
    @Test
    public void isMultiDateTest() {
        // TODO: test isMultiDate
    }

    /**
     * Test the property 'isSingleDay'
     */
    @Test
    public void isSingleDayTest() {
        // TODO: test isSingleDay
    }

    /**
     * Test the property 'isPartOfDay'
     */
    @Test
    public void isPartOfDayTest() {
        // TODO: test isPartOfDay
    }

    /**
     * Test the property 'firstPartOfDay'
     */
    @Test
    public void firstPartOfDayTest() {
        // TODO: test firstPartOfDay
    }

    /**
     * Test the property 'secondPartOfDay'
     */
    @Test
    public void secondPartOfDayTest() {
        // TODO: test secondPartOfDay
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'requestDate'
     */
    @Test
    public void requestDateTest() {
        // TODO: test requestDate
    }

    /**
     * Test the property 'approvalDate'
     */
    @Test
    public void approvalDateTest() {
        // TODO: test approvalDate
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

}
