/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveManagementCreateKitDayRequest
 */
public class LeaveManagementCreateKitDayRequestTest {
    private final LeaveManagementCreateKitDayRequest model = new LeaveManagementCreateKitDayRequest();

    /**
     * Model tests for LeaveManagementCreateKitDayRequest
     */
    @Test
    public void testLeaveManagementCreateKitDayRequest() {
        // TODO: test LeaveManagementCreateKitDayRequest
    }

    /**
     * Test the property 'policyId'
     */
    @Test
    public void policyIdTest() {
        // TODO: test policyId
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'dateFrom'
     */
    @Test
    public void dateFromTest() {
        // TODO: test dateFrom
    }

    /**
     * Test the property 'dateTo'
     */
    @Test
    public void dateToTest() {
        // TODO: test dateTo
    }

}
