/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveManagementListTimeOffRequestsResponseMeta
 */
public class LeaveManagementListTimeOffRequestsResponseMetaTest {
    private final LeaveManagementListTimeOffRequestsResponseMeta model = new LeaveManagementListTimeOffRequestsResponseMeta();

    /**
     * Model tests for LeaveManagementListTimeOffRequestsResponseMeta
     */
    @Test
    public void testLeaveManagementListTimeOffRequestsResponseMeta() {
        // TODO: test LeaveManagementListTimeOffRequestsResponseMeta
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'nextPage'
     */
    @Test
    public void nextPageTest() {
        // TODO: test nextPage
    }

    /**
     * Test the property 'previousPage'
     */
    @Test
    public void previousPageTest() {
        // TODO: test previousPage
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'perPage'
     */
    @Test
    public void perPageTest() {
        // TODO: test perPage
    }

    /**
     * Test the property 'totalEntries'
     */
    @Test
    public void totalEntriesTest() {
        // TODO: test totalEntries
    }

}
