/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveManagementListTimeOffPoliciesResponseDataInner
 */
public class LeaveManagementListTimeOffPoliciesResponseDataInnerTest {
    private final LeaveManagementListTimeOffPoliciesResponseDataInner model = new LeaveManagementListTimeOffPoliciesResponseDataInner();

    /**
     * Model tests for LeaveManagementListTimeOffPoliciesResponseDataInner
     */
    @Test
    public void testLeaveManagementListTimeOffPoliciesResponseDataInner() {
        // TODO: test LeaveManagementListTimeOffPoliciesResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'doNotAccrue'
     */
    @Test
    public void doNotAccrueTest() {
        // TODO: test doNotAccrue
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'defaultAllowance'
     */
    @Test
    public void defaultAllowanceTest() {
        // TODO: test defaultAllowance
    }

    /**
     * Test the property 'maxCarryover'
     */
    @Test
    public void maxCarryoverTest() {
        // TODO: test maxCarryover
    }

    /**
     * Test the property 'accrueType'
     */
    @Test
    public void accrueTypeTest() {
        // TODO: test accrueType
    }

}
