/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RecruitmentCreateApplicantWithReferralRequest
 */
public class RecruitmentCreateApplicantWithReferralRequestTest {
    private final RecruitmentCreateApplicantWithReferralRequest model = new RecruitmentCreateApplicantWithReferralRequest();

    /**
     * Model tests for RecruitmentCreateApplicantWithReferralRequest
     */
    @Test
    public void testRecruitmentCreateApplicantWithReferralRequest() {
        // TODO: test RecruitmentCreateApplicantWithReferralRequest
    }

    /**
     * Test the property 'sendThankYouEmail'
     */
    @Test
    public void sendThankYouEmailTest() {
        // TODO: test sendThankYouEmail
    }

    /**
     * Test the property 'applicantFirstName'
     */
    @Test
    public void applicantFirstNameTest() {
        // TODO: test applicantFirstName
    }

    /**
     * Test the property 'applicantLastName'
     */
    @Test
    public void applicantLastNameTest() {
        // TODO: test applicantLastName
    }

    /**
     * Test the property 'applicantEmail'
     */
    @Test
    public void applicantEmailTest() {
        // TODO: test applicantEmail
    }

    /**
     * Test the property 'applicantReferral'
     */
    @Test
    public void applicantReferralTest() {
        // TODO: test applicantReferral
    }

    /**
     * Test the property 'applicantPhoneNumber'
     */
    @Test
    public void applicantPhoneNumberTest() {
        // TODO: test applicantPhoneNumber
    }

    /**
     * Test the property 'applicantSource'
     */
    @Test
    public void applicantSourceTest() {
        // TODO: test applicantSource
    }

    /**
     * Test the property 'applicantAddress'
     */
    @Test
    public void applicantAddressTest() {
        // TODO: test applicantAddress
    }

    /**
     * Test the property 'applicantSummary'
     */
    @Test
    public void applicantSummaryTest() {
        // TODO: test applicantSummary
    }

    /**
     * Test the property 'applicantAttachment'
     */
    @Test
    public void applicantAttachmentTest() {
        // TODO: test applicantAttachment
    }

}
