/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TimesheetsClockInOutRequestClockedTimeYYYYMMDD;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimesheetsClockInOutRequestClockedTime
 */
public class TimesheetsClockInOutRequestClockedTimeTest {
    private final TimesheetsClockInOutRequestClockedTime model = new TimesheetsClockInOutRequestClockedTime();

    /**
     * Model tests for TimesheetsClockInOutRequestClockedTime
     */
    @Test
    public void testTimesheetsClockInOutRequestClockedTime() {
        // TODO: test TimesheetsClockInOutRequestClockedTime
    }

    /**
     * Test the property 'YYYY_MM_DD'
     */
    @Test
    public void YYYY_MM_DDTest() {
        // TODO: test YYYY_MM_DD
    }

}
