/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee;
import com.konfigthis.client.model.LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * LeaveManagementListEmployeesOutTodayResponseDataInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LeaveManagementListEmployeesOutTodayResponseDataInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Double id;

  public static final String SERIALIZED_NAME_POLICY_ID = "policy_id";
  @SerializedName(SERIALIZED_NAME_POLICY_ID)
  private Double policyId;

  public static final String SERIALIZED_NAME_POLICY = "policy";
  @SerializedName(SERIALIZED_NAME_POLICY)
  private LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy policy;

  public static final String SERIALIZED_NAME_EMPLOYEE_ID = "employee_id";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_ID)
  private Double employeeId;

  public static final String SERIALIZED_NAME_EMPLOYEE = "employee";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE)
  private LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee employee;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private String details;

  public static final String SERIALIZED_NAME_IS_MULTI_DATE = "is_multi_date";
  @SerializedName(SERIALIZED_NAME_IS_MULTI_DATE)
  private Boolean isMultiDate;

  public static final String SERIALIZED_NAME_IS_SINGLE_DAY = "is_single_day";
  @SerializedName(SERIALIZED_NAME_IS_SINGLE_DAY)
  private Boolean isSingleDay;

  public static final String SERIALIZED_NAME_IS_PART_OF_DAY = "is_part_of_day";
  @SerializedName(SERIALIZED_NAME_IS_PART_OF_DAY)
  private Boolean isPartOfDay;

  public static final String SERIALIZED_NAME_FIRST_PART_OF_DAY = "first_part_of_day";
  @SerializedName(SERIALIZED_NAME_FIRST_PART_OF_DAY)
  private Boolean firstPartOfDay;

  public static final String SERIALIZED_NAME_SECOND_PART_OF_DAY = "second_part_of_day";
  @SerializedName(SERIALIZED_NAME_SECOND_PART_OF_DAY)
  private Boolean secondPartOfDay;

  public static final String SERIALIZED_NAME_START_DATE = "start_date";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private String startDate;

  public static final String SERIALIZED_NAME_END_DATE = "end_date";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private String endDate;

  public static final String SERIALIZED_NAME_HOURS = "hours";
  @SerializedName(SERIALIZED_NAME_HOURS)
  private Double hours;

  public LeaveManagementListEmployeesOutTodayResponseDataInner() {
  }

  public LeaveManagementListEmployeesOutTodayResponseDataInner id(Double id) {
    
    
    
    
    this.id = id;
    return this;
  }

  public LeaveManagementListEmployeesOutTodayResponseDataInner id(Integer id) {
    
    
    
    
    this.id = id.doubleValue();
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2902504", value = "")

  public Double getId() {
    return id;
  }


  public void setId(Double id) {
    
    
    
    this.id = id;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner policyId(Double policyId) {
    
    
    
    
    this.policyId = policyId;
    return this;
  }

  public LeaveManagementListEmployeesOutTodayResponseDataInner policyId(Integer policyId) {
    
    
    
    
    this.policyId = policyId.doubleValue();
    return this;
  }

   /**
   * Get policyId
   * @return policyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public Double getPolicyId() {
    return policyId;
  }


  public void setPolicyId(Double policyId) {
    
    
    
    this.policyId = policyId;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner policy(LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy policy) {
    
    
    
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy getPolicy() {
    return policy;
  }


  public void setPolicy(LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy policy) {
    
    
    
    this.policy = policy;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner employeeId(Double employeeId) {
    
    
    
    
    this.employeeId = employeeId;
    return this;
  }

  public LeaveManagementListEmployeesOutTodayResponseDataInner employeeId(Integer employeeId) {
    
    
    
    
    this.employeeId = employeeId.doubleValue();
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "")

  public Double getEmployeeId() {
    return employeeId;
  }


  public void setEmployeeId(Double employeeId) {
    
    
    
    this.employeeId = employeeId;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner employee(LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee employee) {
    
    
    
    
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee getEmployee() {
    return employee;
  }


  public void setEmployee(LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee employee) {
    
    
    
    this.employee = employee;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner details(String details) {
    
    
    
    
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Birthday lunch", value = "")

  public String getDetails() {
    return details;
  }


  public void setDetails(String details) {
    
    
    
    this.details = details;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner isMultiDate(Boolean isMultiDate) {
    
    
    
    
    this.isMultiDate = isMultiDate;
    return this;
  }

   /**
   * Get isMultiDate
   * @return isMultiDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getIsMultiDate() {
    return isMultiDate;
  }


  public void setIsMultiDate(Boolean isMultiDate) {
    
    
    
    this.isMultiDate = isMultiDate;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner isSingleDay(Boolean isSingleDay) {
    
    
    
    
    this.isSingleDay = isSingleDay;
    return this;
  }

   /**
   * Get isSingleDay
   * @return isSingleDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsSingleDay() {
    return isSingleDay;
  }


  public void setIsSingleDay(Boolean isSingleDay) {
    
    
    
    this.isSingleDay = isSingleDay;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner isPartOfDay(Boolean isPartOfDay) {
    
    
    
    
    this.isPartOfDay = isPartOfDay;
    return this;
  }

   /**
   * Get isPartOfDay
   * @return isPartOfDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsPartOfDay() {
    return isPartOfDay;
  }


  public void setIsPartOfDay(Boolean isPartOfDay) {
    
    
    
    this.isPartOfDay = isPartOfDay;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner firstPartOfDay(Boolean firstPartOfDay) {
    
    
    
    
    this.firstPartOfDay = firstPartOfDay;
    return this;
  }

   /**
   * Get firstPartOfDay
   * @return firstPartOfDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getFirstPartOfDay() {
    return firstPartOfDay;
  }


  public void setFirstPartOfDay(Boolean firstPartOfDay) {
    
    
    
    this.firstPartOfDay = firstPartOfDay;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner secondPartOfDay(Boolean secondPartOfDay) {
    
    
    
    
    this.secondPartOfDay = secondPartOfDay;
    return this;
  }

   /**
   * Get secondPartOfDay
   * @return secondPartOfDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getSecondPartOfDay() {
    return secondPartOfDay;
  }


  public void setSecondPartOfDay(Boolean secondPartOfDay) {
    
    
    
    this.secondPartOfDay = secondPartOfDay;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner startDate(String startDate) {
    
    
    
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-05-24", value = "")

  public String getStartDate() {
    return startDate;
  }


  public void setStartDate(String startDate) {
    
    
    
    this.startDate = startDate;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner endDate(String endDate) {
    
    
    
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-05-24", value = "")

  public String getEndDate() {
    return endDate;
  }


  public void setEndDate(String endDate) {
    
    
    
    this.endDate = endDate;
  }


  public LeaveManagementListEmployeesOutTodayResponseDataInner hours(Double hours) {
    
    
    
    
    this.hours = hours;
    return this;
  }

  public LeaveManagementListEmployeesOutTodayResponseDataInner hours(Integer hours) {
    
    
    
    
    this.hours = hours.doubleValue();
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3.5", value = "")

  public Double getHours() {
    return hours;
  }


  public void setHours(Double hours) {
    
    
    
    this.hours = hours;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LeaveManagementListEmployeesOutTodayResponseDataInner instance itself
   */
  public LeaveManagementListEmployeesOutTodayResponseDataInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeaveManagementListEmployeesOutTodayResponseDataInner leaveManagementListEmployeesOutTodayResponseDataInner = (LeaveManagementListEmployeesOutTodayResponseDataInner) o;
    return Objects.equals(this.id, leaveManagementListEmployeesOutTodayResponseDataInner.id) &&
        Objects.equals(this.policyId, leaveManagementListEmployeesOutTodayResponseDataInner.policyId) &&
        Objects.equals(this.policy, leaveManagementListEmployeesOutTodayResponseDataInner.policy) &&
        Objects.equals(this.employeeId, leaveManagementListEmployeesOutTodayResponseDataInner.employeeId) &&
        Objects.equals(this.employee, leaveManagementListEmployeesOutTodayResponseDataInner.employee) &&
        Objects.equals(this.details, leaveManagementListEmployeesOutTodayResponseDataInner.details) &&
        Objects.equals(this.isMultiDate, leaveManagementListEmployeesOutTodayResponseDataInner.isMultiDate) &&
        Objects.equals(this.isSingleDay, leaveManagementListEmployeesOutTodayResponseDataInner.isSingleDay) &&
        Objects.equals(this.isPartOfDay, leaveManagementListEmployeesOutTodayResponseDataInner.isPartOfDay) &&
        Objects.equals(this.firstPartOfDay, leaveManagementListEmployeesOutTodayResponseDataInner.firstPartOfDay) &&
        Objects.equals(this.secondPartOfDay, leaveManagementListEmployeesOutTodayResponseDataInner.secondPartOfDay) &&
        Objects.equals(this.startDate, leaveManagementListEmployeesOutTodayResponseDataInner.startDate) &&
        Objects.equals(this.endDate, leaveManagementListEmployeesOutTodayResponseDataInner.endDate) &&
        Objects.equals(this.hours, leaveManagementListEmployeesOutTodayResponseDataInner.hours)&&
        Objects.equals(this.additionalProperties, leaveManagementListEmployeesOutTodayResponseDataInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, policyId, policy, employeeId, employee, details, isMultiDate, isSingleDay, isPartOfDay, firstPartOfDay, secondPartOfDay, startDate, endDate, hours, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeaveManagementListEmployeesOutTodayResponseDataInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    isMultiDate: ").append(toIndentedString(isMultiDate)).append("\n");
    sb.append("    isSingleDay: ").append(toIndentedString(isSingleDay)).append("\n");
    sb.append("    isPartOfDay: ").append(toIndentedString(isPartOfDay)).append("\n");
    sb.append("    firstPartOfDay: ").append(toIndentedString(firstPartOfDay)).append("\n");
    sb.append("    secondPartOfDay: ").append(toIndentedString(secondPartOfDay)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("policy_id");
    openapiFields.add("policy");
    openapiFields.add("employee_id");
    openapiFields.add("employee");
    openapiFields.add("details");
    openapiFields.add("is_multi_date");
    openapiFields.add("is_single_day");
    openapiFields.add("is_part_of_day");
    openapiFields.add("first_part_of_day");
    openapiFields.add("second_part_of_day");
    openapiFields.add("start_date");
    openapiFields.add("end_date");
    openapiFields.add("hours");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LeaveManagementListEmployeesOutTodayResponseDataInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LeaveManagementListEmployeesOutTodayResponseDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LeaveManagementListEmployeesOutTodayResponseDataInner is not found in the empty JSON string", LeaveManagementListEmployeesOutTodayResponseDataInner.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `policy`
      if (jsonObj.get("policy") != null && !jsonObj.get("policy").isJsonNull()) {
        LeaveManagementListEmployeesOutTodayResponseDataInnerPolicy.validateJsonObject(jsonObj.getAsJsonObject("policy"));
      }
      // validate the optional field `employee`
      if (jsonObj.get("employee") != null && !jsonObj.get("employee").isJsonNull()) {
        LeaveManagementListEmployeesOutTodayResponseDataInnerEmployee.validateJsonObject(jsonObj.getAsJsonObject("employee"));
      }
      if ((jsonObj.get("details") != null && !jsonObj.get("details").isJsonNull()) && !jsonObj.get("details").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `details` to be a primitive type in the JSON string but got `%s`", jsonObj.get("details").toString()));
      }
      if ((jsonObj.get("start_date") != null && !jsonObj.get("start_date").isJsonNull()) && !jsonObj.get("start_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `start_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start_date").toString()));
      }
      if ((jsonObj.get("end_date") != null && !jsonObj.get("end_date").isJsonNull()) && !jsonObj.get("end_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `end_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("end_date").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LeaveManagementListEmployeesOutTodayResponseDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LeaveManagementListEmployeesOutTodayResponseDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LeaveManagementListEmployeesOutTodayResponseDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LeaveManagementListEmployeesOutTodayResponseDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<LeaveManagementListEmployeesOutTodayResponseDataInner>() {
           @Override
           public void write(JsonWriter out, LeaveManagementListEmployeesOutTodayResponseDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LeaveManagementListEmployeesOutTodayResponseDataInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LeaveManagementListEmployeesOutTodayResponseDataInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LeaveManagementListEmployeesOutTodayResponseDataInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LeaveManagementListEmployeesOutTodayResponseDataInner
  * @throws IOException if the JSON string is invalid with respect to LeaveManagementListEmployeesOutTodayResponseDataInner
  */
  public static LeaveManagementListEmployeesOutTodayResponseDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LeaveManagementListEmployeesOutTodayResponseDataInner.class);
  }

 /**
  * Convert an instance of LeaveManagementListEmployeesOutTodayResponseDataInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

