/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * LeaveManagementUpdateKitDaysConfigurationRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LeaveManagementUpdateKitDaysConfigurationRequest {
  /**
   * Whether the policy allows Kit days or not
   */
  @JsonAdapter(KitDaysEnabledEnum.Adapter.class)
 public enum KitDaysEnabledEnum {
    TRUE("true"),
    
    FALSE("false");

    private Boolean value;

    KitDaysEnabledEnum(Boolean value) {
      this.value = value;
    }

    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KitDaysEnabledEnum fromValue(Boolean value) {
      for (KitDaysEnabledEnum b : KitDaysEnabledEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KitDaysEnabledEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KitDaysEnabledEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KitDaysEnabledEnum read(final JsonReader jsonReader) throws IOException {
        Boolean value =  jsonReader.nextBoolean();
        return KitDaysEnabledEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_KIT_DAYS_ENABLED = "kit_days_enabled";
  @SerializedName(SERIALIZED_NAME_KIT_DAYS_ENABLED)
  private KitDaysEnabledEnum kitDaysEnabled;

  public static final String SERIALIZED_NAME_KIT_DAYS_QUANTITY = "kit_days_quantity";
  @SerializedName(SERIALIZED_NAME_KIT_DAYS_QUANTITY)
  private Integer kitDaysQuantity;

  public LeaveManagementUpdateKitDaysConfigurationRequest() {
  }

  public LeaveManagementUpdateKitDaysConfigurationRequest kitDaysEnabled(KitDaysEnabledEnum kitDaysEnabled) {
    
    
    
    
    this.kitDaysEnabled = kitDaysEnabled;
    return this;
  }

   /**
   * Whether the policy allows Kit days or not
   * @return kitDaysEnabled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "TRUE", required = true, value = "Whether the policy allows Kit days or not")

  public KitDaysEnabledEnum getKitDaysEnabled() {
    return kitDaysEnabled;
  }


  public void setKitDaysEnabled(KitDaysEnabledEnum kitDaysEnabled) {
    
    
    
    this.kitDaysEnabled = kitDaysEnabled;
  }


  public LeaveManagementUpdateKitDaysConfigurationRequest kitDaysQuantity(Integer kitDaysQuantity) {
    
    
    
    
    this.kitDaysQuantity = kitDaysQuantity;
    return this;
  }

   /**
   * Maximum number of Kit days allowed in the policy
   * @return kitDaysQuantity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "5", required = true, value = "Maximum number of Kit days allowed in the policy")

  public Integer getKitDaysQuantity() {
    return kitDaysQuantity;
  }


  public void setKitDaysQuantity(Integer kitDaysQuantity) {
    
    
    
    this.kitDaysQuantity = kitDaysQuantity;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LeaveManagementUpdateKitDaysConfigurationRequest instance itself
   */
  public LeaveManagementUpdateKitDaysConfigurationRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeaveManagementUpdateKitDaysConfigurationRequest leaveManagementUpdateKitDaysConfigurationRequest = (LeaveManagementUpdateKitDaysConfigurationRequest) o;
    return Objects.equals(this.kitDaysEnabled, leaveManagementUpdateKitDaysConfigurationRequest.kitDaysEnabled) &&
        Objects.equals(this.kitDaysQuantity, leaveManagementUpdateKitDaysConfigurationRequest.kitDaysQuantity)&&
        Objects.equals(this.additionalProperties, leaveManagementUpdateKitDaysConfigurationRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kitDaysEnabled, kitDaysQuantity, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeaveManagementUpdateKitDaysConfigurationRequest {\n");
    sb.append("    kitDaysEnabled: ").append(toIndentedString(kitDaysEnabled)).append("\n");
    sb.append("    kitDaysQuantity: ").append(toIndentedString(kitDaysQuantity)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kit_days_enabled");
    openapiFields.add("kit_days_quantity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("kit_days_enabled");
    openapiRequiredFields.add("kit_days_quantity");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LeaveManagementUpdateKitDaysConfigurationRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LeaveManagementUpdateKitDaysConfigurationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LeaveManagementUpdateKitDaysConfigurationRequest is not found in the empty JSON string", LeaveManagementUpdateKitDaysConfigurationRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LeaveManagementUpdateKitDaysConfigurationRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LeaveManagementUpdateKitDaysConfigurationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LeaveManagementUpdateKitDaysConfigurationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LeaveManagementUpdateKitDaysConfigurationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LeaveManagementUpdateKitDaysConfigurationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<LeaveManagementUpdateKitDaysConfigurationRequest>() {
           @Override
           public void write(JsonWriter out, LeaveManagementUpdateKitDaysConfigurationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LeaveManagementUpdateKitDaysConfigurationRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LeaveManagementUpdateKitDaysConfigurationRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LeaveManagementUpdateKitDaysConfigurationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LeaveManagementUpdateKitDaysConfigurationRequest
  * @throws IOException if the JSON string is invalid with respect to LeaveManagementUpdateKitDaysConfigurationRequest
  */
  public static LeaveManagementUpdateKitDaysConfigurationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LeaveManagementUpdateKitDaysConfigurationRequest.class);
  }

 /**
  * Convert an instance of LeaveManagementUpdateKitDaysConfigurationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

