/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.IntegrationsImportNewStartersListResponse;
import com.konfigthis.client.model.IntegrationsSendBonusesToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferAppointmentInfoResponse;
import com.konfigthis.client.model.IntegrationsTransferBankAccountInfoResponse;
import com.konfigthis.client.model.IntegrationsTransferContractInformationToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferJobPositionFromSageToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferLeaveInformationToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferOrganizationalStructureFromSageToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferSalaryInformationResponse;
import com.konfigthis.client.model.IntegrationsTransferTerminationInfoToVikarinaResponse;
import com.konfigthis.client.model.IntegrationsTransferTimeScheduleInformationResponse;
import com.konfigthis.client.model.IntegrationsTransferUnusedVacationDaysToVikarinaResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IntegrationsApi
 */
@Disabled
public class IntegrationsApiTest {

    private static IntegrationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new IntegrationsApi(apiClient);
    }

    /**
     * New starters list from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importNewStartersListTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsImportNewStartersListResponse response = api.importNewStartersList()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Sending bonuses [payed once] to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendBonusesToVikarinaTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsSendBonusesToVikarinaResponse response = api.sendBonusesToVikarina()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * New appointment (position changes) information transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferAppointmentInfoTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsTransferAppointmentInfoResponse response = api.transferAppointmentInfo()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Bank account information transfer (Custom field) from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferBankAccountInfoTest() throws ApiException {
        IntegrationsTransferBankAccountInfoResponse response = api.transferBankAccountInfo()
                .execute();
        // TODO: test validations
    }

    /**
     * Contract (custom field) information transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferContractInformationToVikarinaTest() throws ApiException {
        IntegrationsTransferContractInformationToVikarinaResponse response = api.transferContractInformationToVikarina()
                .execute();
        // TODO: test validations
    }

    /**
     * Job position transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferJobPositionFromSageToVikarinaTest() throws ApiException {
        IntegrationsTransferJobPositionFromSageToVikarinaResponse response = api.transferJobPositionFromSageToVikarina()
                .execute();
        // TODO: test validations
    }

    /**
     * Leaves information transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferLeaveInformationToVikarinaTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsTransferLeaveInformationToVikarinaResponse response = api.transferLeaveInformationToVikarina()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Organizational structure transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferOrganizationalStructureFromSageToVikarinaTest() throws ApiException {
        IntegrationsTransferOrganizationalStructureFromSageToVikarinaResponse response = api.transferOrganizationalStructureFromSageToVikarina()
                .execute();
        // TODO: test validations
    }

    /**
     * Salary information transfer from Sage HR to Vikarina to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferSalaryInformationTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsTransferSalaryInformationResponse response = api.transferSalaryInformation()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Termination information transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferTerminationInfoToVikarinaTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsTransferTerminationInfoToVikarinaResponse response = api.transferTerminationInfoToVikarina()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Time Schedule information transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferTimeScheduleInformationTest() throws ApiException {
        String startDate = null;
        String endDate = null;
        IntegrationsTransferTimeScheduleInformationResponse response = api.transferTimeScheduleInformation()
                .startDate(startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * Unused vacation days transfer from Sage HR to Vikarina
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transferUnusedVacationDaysToVikarinaTest() throws ApiException {
        IntegrationsTransferUnusedVacationDaysToVikarinaResponse response = api.transferUnusedVacationDaysToVikarina()
                .execute();
        // TODO: test validations
    }

}
