/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.OffboardingCreateTaskRequest;
import com.konfigthis.client.model.OffboardingCreateTaskResponse;
import com.konfigthis.client.model.OffboardingListCategoriesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OffboardingApi
 */
@Disabled
public class OffboardingApiTest {

    private static OffboardingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OffboardingApi(apiClient);
    }

    /**
     * Create new offboarding task
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTaskTest() throws ApiException {
        String title = null;
        Double boardingTaskTemplateCategoryId = null;
        Double dueIn = null;
        String description = null;
        String defaultAssigneeType = null;
        Double assigneeId = null;
        String requireAttachment = null;
        OffboardingCreateTaskResponse response = api.createTask(title, boardingTaskTemplateCategoryId, dueIn)
                .description(description)
                .defaultAssigneeType(defaultAssigneeType)
                .assigneeId(assigneeId)
                .requireAttachment(requireAttachment)
                .execute();
        // TODO: test validations
    }

    /**
     * List offboarding task categories
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCategoriesTest() throws ApiException {
        OffboardingListCategoriesResponse response = api.listCategories()
                .execute();
        // TODO: test validations
    }

}
