/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.PerformanceGetQuarterlyCompanyGoalsResponse;
import com.konfigthis.client.model.PerformanceGetQuarterlyIndividualGoalsResponse;
import com.konfigthis.client.model.PerformanceGetQuarterlyTeamGoalsResponse;
import com.konfigthis.client.model.PerformanceOverviewQuarterlyProgressResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PerformanceApi
 */
@Disabled
public class PerformanceApiTest {

    private static PerformanceApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PerformanceApi(apiClient);
    }

    /**
     * Quarterly company goals
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQuarterlyCompanyGoalsTest() throws ApiException {
        PerformanceGetQuarterlyCompanyGoalsResponse response = api.getQuarterlyCompanyGoals()
                .execute();
        // TODO: test validations
    }

    /**
     * Quarterly individual goals
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQuarterlyIndividualGoalsTest() throws ApiException {
        PerformanceGetQuarterlyIndividualGoalsResponse response = api.getQuarterlyIndividualGoals()
                .execute();
        // TODO: test validations
    }

    /**
     * Quarterly team goals
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQuarterlyTeamGoalsTest() throws ApiException {
        PerformanceGetQuarterlyTeamGoalsResponse response = api.getQuarterlyTeamGoals()
                .execute();
        // TODO: test validations
    }

    /**
     * Overview of quarterly goal progress
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void overviewQuarterlyProgressTest() throws ApiException {
        PerformanceOverviewQuarterlyProgressResponse response = api.overviewQuarterlyProgress()
                .execute();
        // TODO: test validations
    }

}
