/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.PositionsListCompanyPositionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PositionsApi
 */
@Disabled
public class PositionsApiTest {

    private static PositionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PositionsApi(apiClient);
    }

    /**
     * List positions in company
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCompanyPositionsTest() throws ApiException {
        Integer page = null;
        PositionsListCompanyPositionsResponse response = api.listCompanyPositions()
                .page(page)
                .execute();
        // TODO: test validations
    }

}
