/*
 * Sage HR API
 * All requests are required to be sent to your subdomain. To learn how to enable API in your Sage HR account, please visit https://support.sage.hr/en/articles/3246469-how-does-cakehr-api-work
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.TimesheetsClockInOutRequest;
import com.konfigthis.client.model.TimesheetsClockInOutRequestClockedTime;
import com.konfigthis.client.model.TimesheetsClockInOutResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TimesheetsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TimesheetsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public TimesheetsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call clockInOutCall(TimesheetsClockInOutRequest timesheetsClockInOutRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = timesheetsClockInOutRequest;

        // create path and map variables
        String localVarPath = "/timesheets/clock-in";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "api_key" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call clockInOutValidateBeforeCall(TimesheetsClockInOutRequest timesheetsClockInOutRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'timesheetsClockInOutRequest' is set
        if (timesheetsClockInOutRequest == null) {
            throw new ApiException("Missing the required parameter 'timesheetsClockInOutRequest' when calling clockInOut(Async)");
        }

        return clockInOutCall(timesheetsClockInOutRequest, _callback);

    }


    private ApiResponse<TimesheetsClockInOutResponse> clockInOutWithHttpInfo(TimesheetsClockInOutRequest timesheetsClockInOutRequest) throws ApiException {
        okhttp3.Call localVarCall = clockInOutValidateBeforeCall(timesheetsClockInOutRequest, null);
        Type localVarReturnType = new TypeToken<TimesheetsClockInOutResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call clockInOutAsync(TimesheetsClockInOutRequest timesheetsClockInOutRequest, final ApiCallback<TimesheetsClockInOutResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = clockInOutValidateBeforeCall(timesheetsClockInOutRequest, _callback);
        Type localVarReturnType = new TypeToken<TimesheetsClockInOutResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ClockInOutRequestBuilder {
        private String override;
        private TimesheetsClockInOutRequestClockedTime clockedTime;

        private ClockInOutRequestBuilder() {
        }

        /**
         * Set override
         * @param override &#39;true&#39; if override provided days clocked entries (optional)
         * @return ClockInOutRequestBuilder
         */
        public ClockInOutRequestBuilder override(String override) {
            this.override = override;
            return this;
        }
        
        /**
         * Set clockedTime
         * @param clockedTime  (optional)
         * @return ClockInOutRequestBuilder
         */
        public ClockInOutRequestBuilder clockedTime(TimesheetsClockInOutRequestClockedTime clockedTime) {
            this.clockedTime = clockedTime;
            return this;
        }
        
        /**
         * Build call for clockInOut
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            TimesheetsClockInOutRequest timesheetsClockInOutRequest = buildBodyParams();
            return clockInOutCall(timesheetsClockInOutRequest, _callback);
        }

        private TimesheetsClockInOutRequest buildBodyParams() {
            TimesheetsClockInOutRequest timesheetsClockInOutRequest = new TimesheetsClockInOutRequest();
            timesheetsClockInOutRequest.override(this.override);
            timesheetsClockInOutRequest.clockedTime(this.clockedTime);
            return timesheetsClockInOutRequest;
        }

        /**
         * Execute clockInOut request
         * @return TimesheetsClockInOutResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public TimesheetsClockInOutResponse execute() throws ApiException {
            TimesheetsClockInOutRequest timesheetsClockInOutRequest = buildBodyParams();
            ApiResponse<TimesheetsClockInOutResponse> localVarResp = clockInOutWithHttpInfo(timesheetsClockInOutRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute clockInOut request with HTTP info returned
         * @return ApiResponse&lt;TimesheetsClockInOutResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<TimesheetsClockInOutResponse> executeWithHttpInfo() throws ApiException {
            TimesheetsClockInOutRequest timesheetsClockInOutRequest = buildBodyParams();
            return clockInOutWithHttpInfo(timesheetsClockInOutRequest);
        }

        /**
         * Execute clockInOut request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<TimesheetsClockInOutResponse> _callback) throws ApiException {
            TimesheetsClockInOutRequest timesheetsClockInOutRequest = buildBodyParams();
            return clockInOutAsync(timesheetsClockInOutRequest, _callback);
        }
    }

    /**
     * Clock in &amp; out employees on specific days
     * Employees will be only clocked in &amp; out if API time clocking is enabled for Timesheet group
     * @param timesheetsClockInOutRequest Times on specific dates for specific employees as json (required)
     * @return ClockInOutRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ClockInOutRequestBuilder clockInOut() throws IllegalArgumentException {
        return new ClockInOutRequestBuilder();
    }
}
